# Generated by Django 6.0.3 on 2026-03-10 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[('uuid', models.UUIDField(
                db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('status', models.TextField(
                    choices=[('QUEUED', 'queued'),
                             ('PROCESSING', 'processing'),
                             ('COMPLETE', 'complete')],
                    default='QUEUED')),
                ('object_key', models.TextField()),],),]
