# Generated by Django 6.0.3 on 2026-03-11 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[('uuid', models.UUIDField(
                db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('status', models.TextField(
                    choices=[('QUEUED', 'queued'),
                             ('PROCESSING', 'processing'),
                             ('COMPLETE', 'complete'),
                             ('FAILED', 'failed')],
                    default='QUEUED')),
                ('object_key', models.TextField()),
                ('time_ingested', models.DateTimeField(auto_now_add=True, verbose_name='Time ingested')),
                ('time_processed', models.DateTimeField(auto_now=True, verbose_name='Time processed')),],),]
