# Generated by Django 6.0.3 on 2026-03-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_DataFile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='error_msg',
            field=models.TextField(default=''),
        ),
    ]
