---
apiVersion: v1
kind: Service
metadata:
  name: celery-flower
spec:
  selector:
    app.kubernetes.io/name: celery-flower
  ports:
  - port: {{ .Values.celery.flower.port }}
    protocol: TCP
    targetPort: {{ .Values.celery.flower.port }}
